version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile  
    #user: appuser  
    ports:
     - "8050:8050"
    volumes:
      - .:/code
    depends_on:
      - "redis"
    command: ["python", "-u", "app.py"]

  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis