version: '3'
services:
  web:
    build: .
    ports:
     - "8050:8050"
    volumes:
      - .:/code
  redis:
    image: "redis:alpine"
    # environment: 
    #   - FLUSHALL=yes
    # command: ["redis-server", "--appendonly", "yes"]
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis

  rcli:
    image: redis:alpine
    links:
      - redis
    command: >
       sh -c 'redis-cli FLUSHALL '
