version: '3'
services:
  web:
    build: .
    ports:
     - "8050:8050"
    volumes:
      - .:/code
    depends_on:
      - "redis"

  redis:
    image: "redis:alpine"
    # environment: 
    #   - FLUSHALL=yes
    # command: ["redis-server", "--appendonly", "yes"]
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    healthcheck:
      test: redis-server -v
      interval: 1s
      timeout: 5s
      retries: 30

  # rcli:
  #   image: redis:alpine
  #   links:
  #     - redis
  #   command: 
  #      sh -c 'redis-cli FLUSHALL '
