version: '3'
services:
  web:
    build: .
    ports:
     - "8050:8050"
    volumes:
      - .:/code
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis